### ISSUE TITLE
I got spammed when using new version of fuji

### ISSUE THREAD

**Issue by Hiusi** [fuji-fabric/fuji#50]
```
[13:32:06] [DefaultQuartzScheduler_Worker-1/ERROR]: Job io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.d105d515-ece6-486f-9f95-ffc6816e206a threw an unhandled Exception: 
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
```

**Comment by Hiusi** [comment]
The sample of spamming in console
```
[13:42:45] [DefaultQuartzScheduler_Worker-7/ERROR]: Job (io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        ... 1 more
[13:42:46] [DefaultQuartzScheduler_Worker-3/ERROR]: Job io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an unhandled Exception: 
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
[13:42:46] [DefaultQuartzScheduler_Worker-3/ERROR]: Job (io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        ... 1 more
[13:42:47] [DefaultQuartzScheduler_Worker-4/ERROR]: Job io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an unhandled Exception: 
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
[13:42:47] [DefaultQuartzScheduler_Worker-4/ERROR]: Job (io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        ... 1 more
[13:42:48] [DefaultQuartzScheduler_Worker-1/ERROR]: Job io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an unhandled Exception: 
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
[13:42:48] [DefaultQuartzScheduler_Worker-1/ERROR]: Job (io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        ... 1 more
[13:42:49] [DefaultQuartzScheduler_Worker-8/ERROR]: Job io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an unhandled Exception: 
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
[13:42:49] [DefaultQuartzScheduler_Worker-8/ERROR]: Job (io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        ... 1 more
[13:42:50] [DefaultQuartzScheduler_Worker-5/ERROR]: Job io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an unhandled Exception: 
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
[13:42:50] [DefaultQuartzScheduler_Worker-5/ERROR]: Job (io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        ... 1 more
[13:42:51] [DefaultQuartzScheduler_Worker-9/ERROR]: Job io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an unhandled Exception: 
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
[13:42:51] [DefaultQuartzScheduler_Worker-9/ERROR]: Job (io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        ... 1 more
[13:42:52] [DefaultQuartzScheduler_Worker-2/ERROR]: Job io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an unhandled Exception: 
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
[13:42:52] [DefaultQuartzScheduler_Worker-2/ERROR]: Job (io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        ... 1 more
[13:42:53] [DefaultQuartzScheduler_Worker-6/ERROR]: Job io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an unhandled Exception: 
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
[13:42:53] [DefaultQuartzScheduler_Worker-6/ERROR]: Job (io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        ... 1 more
[13:42:54] [DefaultQuartzScheduler_Worker-10/ERROR]: Job io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an unhandled Exception: 
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
[13:42:54] [DefaultQuartzScheduler_Worker-10/ERROR]: Job (io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        ... 1 more
[13:42:55] [DefaultQuartzScheduler_Worker-7/ERROR]: Job io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an unhandled Exception: 
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
[13:42:55] [DefaultQuartzScheduler_Worker-7/ERROR]: Job (io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.b711f2d3-070b-4d2b-88fe-e1303e7901d4 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at io.github.sakurawald.util.minecraft.MessageHelper.ofComponent(MessageHelper.java:208) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.TabListInitializer.render(TabListInitializer.java:41) ~[fuji-1.3.8.jar:?]
        at io.github.sakurawald.module.initializer.tab_list.job.RenderHeaderAndFooterJob.execute(RenderHeaderAndFooterJob.java:19) ~[fuji-1.3.8.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[org_quartz-scheduler_quartz-2.5.0-rc1-457d36ba8c5bd8be.jar:?]
        ... 1 more
container@dolphin~ Server marked as stopping...
```

**Comment by sakurawald** [comment]
Knowed issue, please use the `v1.3.8` vresion.

**Comment by sakurawald** [comment]
Please provide the `logs`, it seem like the missing java library `adventure tect`, which should not happen, since this library is included in the mod.

**Comment by Hiusi** [comment]
Sorry for not provide the log,
server log:
[2024-08-03-6.log](https://github.com/user-attachments/files/16478847/2024-08-03-6.log)

**Comment by sakurawald** [comment]
Can you provide the version of server core you you are using ?

**Comment by sakurawald** [comment]
I check the logs, all the necessary libraries is included in the mod, but one of the library named `adventure text` can't find the target class, and the mixin files is not injected into it.

**Comment by Hiusi** [comment]
what is server core? do you mean this mod? https://modrinth.com/mod/servercore
if yes I did not use servercore
to be honest I updated 8 mods, and since then I get that spam log, I will try to revert it all
nature spirit 1.6.0
Nature Compass 2.2.6
Friends And Foe 2.0.15
Dungeon and Taverns
Wilder Wild
Lootr
Graves
Fuji

**Comment by sakurawald** [comment]
The error is from `tablist` module. Does this module cause error in `v1.3.7` version ?

I just test the `fabric` server core with `fabric-loader-0.16.0` and `fabric-api 0.100.8+1.21`, all works fine in my environment.

It's like some mods conflits, and i don't understand why there are so many warnings about `no class found`, which is strange.

The spam is from `tablist module`, since one of the library fuji used, can't inject its methods into the target class, so each time the tablist is updated, the `can' t find target method exception` will be throw.

**Comment by sakurawald** [comment]
> what is server core? do you mean this mod? https://modrinth.com/mod/servercore if yes I did not use servercore to be honest I updated 8 mods, and since then I get that spam log, I will try to revert it all nature spirit 1.6.0 Nature Compass 2.2.6 Friends And Foe 2.0.15 Dungeon and Taverns Wilder Wild Lootr Graves Fuji

The server core, i mean, if you are using the pure `fabric` server core, or anything `hybrid server core` like `mohist`/`banner`

**Comment by sakurawald** [comment]
> what is server core? do you mean this mod? https://modrinth.com/mod/servercore if yes I did not use servercore to be honest I updated 8 mods, and since then I get that spam log, I will try to revert it all nature spirit 1.6.0 Nature Compass 2.2.6 Friends And Foe 2.0.15 Dungeon and Taverns Wilder Wild Lootr Graves Fuji

Yeah, it's recommended you to revert the changes, and find out which mod cause the conflicts.

**Comment by sakurawald** [comment]
The mod `Wilder Wild v2.4.8 mc1.21` conflicts with the library `adventure-text`, all other mods use this library, will all occur the same problem.
Similar issue: https://github.com/FrozenBlock/WilderWild/issues/289

**Comment by Hiusi** [comment]
Interesting! I will revert it then, thank you for your help I will remove wilder wilds and I use pure fabric

**Comment by sakurawald** [comment]
We have use a workaround solution to solve this: written the tablist update packet sending logic using vanilla functions, without the using of `adventure library`.
So you can install `Wilder Wild` mod with `tablist module` provided by fuji.
Or you can just disable `tablist module` and using other mods that provide the same function.

**Comment by sakurawald** [comment]
> Interesting! I will revert it then, thank you for your help I will remove wilder wilds and I use pure fabric

We have use a workaround solution to solve this: written the tablist update packet sending logic using vanilla functions, without the using of adventure library.
So you can install Wilder Wild mod with tablist module provided by fuji.
Or you can just disable tablist module and using other mods that provide the same function.
