### ISSUE TITLE
Compatability issue with StyledChat

### ISSUE THREAD

**Issue by fucksophie** [fuji-fabric/fuji#65]
```
[12:18:37] [Server thread/INFO]: yxguden[/<>:46892] logged in with entity id 14 at (178.77333698113645, 68.0, -59.32733537851118)
[12:18:37] [Server thread/ERROR]: Couldn't place player in world
java.lang.ClassCastException: class net.minecraft.class_8828$class_2585 cannot be cast to class net.minecraft.class_2588 (net.minecraft.class_8828$class_2585 and net.minecraft.class_2588 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3c756e4d)
        at net.minecraft.class_3324.modify$bdj000$styledchat$styledChat_updatePlayerNameAfterMessage(class_3324.java:7024) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:221) ~[server-intermediary.jar:?]
        at net.minecraft.class_8610.method_52408(class_8610.java:152) ~[server-intermediary.jar:?]
        at net.minecraft.class_8736.method_53043(class_8736.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_8736.method_11054(class_8736.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
        ````

**Comment by sakurawald** [comment]
Try disable the module `system_message`.

I will fix this later.

**Comment by sakurawald** [comment]
See also: https://github.com/Patbox/StyledChat/issues/54

The solution is here: 
1. Before `fuji v1.5.0`, disable the module `system_message` if you are using `StyledChat`.
2. After `fuji v1.5.0`, you can enable the module `system_message`, but remember to remove the conflicting system-message keys inside `key2value` configuration. (e.g. remove the `multiplayer.player.joined` and `multiplayer.player.left`)
